POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJ4QGdtYWlsLmNvbSIsImlkIjozLCJpYXQiOjE2ODYyMzY5MTl9.fsiigwJRusc4QZVLapowaoHWezH2wIHkl3q8GCpZ6_k

{
  "author": "Muu Muu",
  "url": "www.notread.fi",
  "title": "this blog will be also be marked read",
  "year": 2007
}